const products = [ 
{
 id:"adama-bague-1", 
 dimension:"3x3x2", 
 material:"argent", 
 size:"54", 
 stone:"améthyste verte",
 treatment:"plaqué or", 
 weight:"36.6", 
 name:"Bague Naïade", 
 price:"1400" 
}, 
{
 id:"adama-collier-1", 
 dimension:"4.5", 
 material:"bronze", 
 size:"", 
 stone:"améthyste verte & tourmaline ",
 treatment:"doré a l’or fin", 
 weight:"29.5", 
 name:"Pendentif Naïade", 
 price:"950" 
}, 
{
 id:"adama-bague-2", 
 dimension:"2.5x3x4.5", 
 material:"argent", 
 size:"57", 
 stone:"malachite avec signature émeraude ",
 treatment:"plaqué or", 
 weight:"34", 
 name:"Bague Perseï", 
 price:"1400" 
}, 
{
 id:"adama-collier-2", 
 dimension:"12", 
 material:"bronze", 
 size:"", 
 stone:"malachites",
 treatment:"doré a l’or fin", 
 weight:"", 
 name:"Collier Perseï", 
 price:"2500" 
}, 
{
 id:"adama-manchette-1", 
 dimension:"6.5x11", 
 material:"bronze", 
 size:"", 
 stone:"malachite",
 treatment:"doré a l’or fin", 
 weight:"152.4", 
 name:"Manchette Perseï", 
 price:"1600" 
}, 
{
 id:"adama-collier-4", 
 dimension:"4.5", 
 material:"bronze", 
 size:"", 
 stone:"malachite",
 treatment:"doré a l’or fin", 
 weight:"20.4", 
 name:"Pendentif Perseï II", 
 price:"750" 
}, 
{
 id:"adama-bague-3", 
 dimension:"3.3x2.5x4.2", 
 material:"argent", 
 size:"", 
 stone:"dioptase avec signature émeraude ",
 treatment:"plaqué or", 
 weight:"36", 
 name:"Bague Tara I", 
 price:"1600" 
}, 
{
 id:"adama-bague-4", 
 dimension:"3.2x3x3.5", 
 material:"argent", 
 size:"60", 
 stone:"dioptase avec signature émeraude",
 treatment:"plaqué or", 
 weight:"37", 
 name:"Bague Tara II", 
 price:"1400" 
}, 
{
 id:"adama-collier-5", 
 dimension:"12", 
 material:"bronze", 
 size:"", 
 stone:"dioptases & lolites",
 treatment:"doré a l’or fin", 
 weight:"290", 
 name:"Collier Tara I", 
 price:"Sur demande" 
}, 
{
 id:"adama-collier-6", 
 dimension:"13", 
 material:"bronze", 
 size:"", 
 stone:"dioptases",
 treatment:"doré a l’or fin", 
 weight:"300", 
 name:"Collier Tara II", 
 price:"Sur demande" 
}, 
{
 id:"adama-manchette-3", 
 dimension:"9", 
 material:"argent", 
 size:"", 
 stone:"dioptase avec  signature émeraude",
 treatment:"doré a l’or fin", 
 weight:"237", 
 name:"Manchette Tara I", 
 price:"2500" 
}, 
{
 id:"adama-manchette-4", 
 dimension:"9", 
 material:"argent", 
 size:"", 
 stone:"dioptase avec  signature émeraude",
 treatment:"doré a l’or fin", 
 weight:"262.6", 
 name:"Manchette Tara II", 
 price:"2500" 
}, 
{
 id:"adama-collier-7", 
 dimension:"7", 
 material:"bronze", 
 size:"", 
 stone:"dioptase",
 treatment:"doré a l’or fin", 
 weight:"95", 
 name:"Pendentif Tara", 
 price:"1000" 
}, 
{
 id:"altair-bague-1", 
 dimension:"3.2x3x4", 
 material:"argent", 
 size:"58", 
 stone:"agate cristallisée",
 treatment:"plaqué or", 
 weight:"56", 
 name:"Bague Alnaïr I", 
 price:"1400" 
}, 
{
 id:"altair-bague-2", 
 dimension:"3x2.5x5", 
 material:"argent", 
 size:"53", 
 stone:"agate cristallisée",
 treatment:"plaqué or", 
 weight:"61", 
 name:"Bague Alnaïr II", 
 price:"1400" 
}, 
{
 id:"altair-bague-3", 
 dimension:"3x3x3.5", 
 material:"argent", 
 size:"53", 
 stone:"agate cristallisée",
 treatment:"plaqué or", 
 weight:"58", 
 name:"Bague Alnaïr III", 
 price:"1400" 
}, 
{
 id:"altair-manchette-1", 
 dimension:"11.5x6", 
 material:"bronze", 
 size:"", 
 stone:"agate cristallisée",
 treatment:"doré a l’or fin", 
 weight:"177.7", 
 name:"Manchette Alnaïr I", 
 price:"1600" 
}, 
{
 id:"altair-manchette-2", 
 dimension:"8x6", 
 material:"bronze", 
 size:"", 
 stone:"agate cristallisée",
 treatment:"doré a l’or fin", 
 weight:"190", 
 name:"Manchette Alnaïr II", 
 price:"1600" 
}, 
{
 id:"altair-collier-1", 
 dimension:"6", 
 material:"bronze", 
 size:"", 
 stone:"agate cristallisée",
 treatment:"doré a l’or fin", 
 weight:"43", 
 name:"Pendentif Alnaïr I", 
 price:"750" 
}, 
{
 id:"altair-bague-4", 
 dimension:"4x4x3", 
 material:"bronze", 
 size:"56", 
 stone:"quartz rutile",
 treatment:"plaqué or", 
 weight:"38.7", 
 name:"Bague Eridani", 
 price:"900" 
}, 
{
 id:"altair-manchette-3", 
 dimension:"9x6", 
 material:"bronze", 
 size:"", 
 stone:"agate",
 treatment:"doré a l’or fin", 
 weight:"180", 
 name:"Manchette Izar", 
 price:"1600" 
}, 
{
 id:"altair-bague-5", 
 dimension:"4.5x2.8x2.3", 
 material:"argent", 
 size:"54", 
 stone:"cristal de roche",
 treatment:"plaqué or", 
 weight:"46.7", 
 name:"Bague Vega I", 
 price:"1200" 
}, 
{
 id:"altair-bague-6", 
 dimension:"4.5x2.5x2.2", 
 material:"argent", 
 size:"55", 
 stone:"cristal de roche",
 treatment:"plaqué or", 
 weight:"41.1", 
 name:"Bague Vega II", 
 price:"1200" 
}, 
{
 id:"altair-bague-7", 
 dimension:"4.8x2.5x2.5", 
 material:"argent", 
 size:"55", 
 stone:"cristal de roche",
 treatment:"plaqué or", 
 weight:"40.5", 
 name:"Bague Vega III", 
 price:"1200" 
}, 
{
 id:"antares-manchette-1", 
 dimension:"7x6", 
 material:"bronze", 
 size:"", 
 stone:"améthystes & citrine",
 treatment:"doré a l’or fin", 
 weight:"173", 
 name:"Manchette Cassiopée", 
 price:"1400" 
}, 
{
 id:"antares-collier-1", 
 dimension:"13", 
 material:"bronze", 
 size:"", 
 stone:"améthyste brute",
 treatment:"doré a l’or fin", 
 weight:"319", 
 name:"Collier Io", 
 price:"Sur demande" 
}, 
{
 id:"antares-manchette-2", 
 dimension:"7.5x6", 
 material:"bronze", 
 size:"", 
 stone:"une tranche d’améthyste 79,95 carrats avec signature diamant noir",
 treatment:"doré a l’or fin", 
 weight:"157.2", 
 name:"Manchette Io", 
 price:"1800" 
}, 
{
 id:"antares-bague-1", 
 dimension:"3.5x2.3x3.5", 
 material:"argent", 
 size:"56", 
 stone:"rubis & pierre de lune",
 treatment:"plaqué or", 
 weight:"54", 
 name:"Bague Mira", 
 price:"1400" 
}, 
{
 id:"antares-manchette-3", 
 dimension:"8x6", 
 material:"bronze", 
 size:"", 
 stone:"rubis chatoyant",
 treatment:"doré a l’or fin", 
 weight:"179.3", 
 name:"Manchette Mira", 
 price:"1800" 
}, 
{
 id:"bellatrix-bague-1", 
 dimension:"3.3x2.2x2", 
 material:"argent", 
 size:"58", 
 stone:"aigue-marine",
 treatment:"plaqué or", 
 weight:"33.8", 
 name:"Bague Adara", 
 price:"1100" 
}, 
{
 id:"bellatrix-bague-2", 
 dimension:"3.3x3.5x3", 
 material:"argent", 
 size:"55", 
 stone:"célestine brut",
 treatment:"plaqué or", 
 weight:"44", 
 name:"Bague Alcyone", 
 price:"1400" 
}, 
{
 id:"bellatrix-bague-3", 
 dimension:"3.2x2.7x3.6", 
 material:"argent", 
 size:"55", 
 stone:"azurite avec signature saphir",
 treatment:"plaqué or", 
 weight:"47", 
 name:"Bague Eta", 
 price:"1400" 
}, 
{
 id:"bellatrix-manchette-1", 
 dimension:"9x6", 
 material:"bronze", 
 size:"", 
 stone:"azurite",
 treatment:"doré a l’or fin", 
 weight:"229.2", 
 name:"Manchette Eta", 
 price:"1800" 
}, 
{
 id:"bellatrix-bague-4", 
 dimension:"3.7x3.9x2.7", 
 material:"argent", 
 size:"54", 
 stone:"aigue-marine 81 carrats avec signature saphir",
 treatment:"plaqué or", 
 weight:"63", 
 name:"Bague Meissa", 
 price:"2500" 
}, 
{
 id:"bellatrix-bague-5", 
 dimension:"3x4x2.5", 
 material:"argent", 
 size:"57", 
 stone:"lapis-lazuli",
 treatment:"plaqué or", 
 weight:"36.2", 
 name:"Bague Rho I", 
 price:"1300" 
}, 
{
 id:"bellatrix-bague-6", 
 dimension:"3.3x2.3x3", 
 material:"argent", 
 size:"54", 
 stone:"lapis-lazuli",
 treatment:"plaqué or", 
 weight:"27.5", 
 name:"Bague Rho II", 
 price:"1200" 
}, 
{
 id:"bellatrix-collier-1", 
 dimension:"12", 
 material:"bronze", 
 size:"", 
 stone:"lapis-lazuli",
 treatment:"doré a l’or fin", 
 weight:"207.4", 
 name:"Collier Rho", 
 price:"2500" 
}, 
{
 id:"bellatrix-bague-7", 
 dimension:"5.5x2.5x2.5", 
 material:"argent", 
 size:"60", 
 stone:"azurite brute",
 treatment:"plaqué or", 
 weight:"41.7", 
 name:"Bague Tauri A", 
 price:"1600" 
}, 
{
 id:"bellatrix-bague-8", 
 dimension:"4x3x2.5", 
 material:"argent", 
 size:"56", 
 stone:"azurite brute",
 treatment:"plaqué or", 
 weight:"38.2", 
 name:"Bague Tauri B", 
 price:"1600" 
}, 
{
 id:"bellatrix-bague-9", 
 dimension:"4.2x3x2.6", 
 material:"argent", 
 size:"59", 
 stone:"azurite brute",
 treatment:"plaqué or", 
 weight:"47", 
 name:"Bague Tauri I", 
 price:"1400" 
}, 
{
 id:"bellatrix-bague-10", 
 dimension:"3.3x2.7x2.6", 
 material:"argent", 
 size:"58", 
 stone:"azurite brute",
 treatment:"plaqué or", 
 weight:"40", 
 name:"Bague Tauri II", 
 price:"1400" 
}, 
{
 id:"bellatrix-manchette-2", 
 dimension:"6x6", 
 material:"bronze", 
 size:"", 
 stone:"azurite brute",
 treatment:"doré a l’or fin", 
 weight:"151.9", 
 name:"Manchette Tauri", 
 price:"1600" 
}, 
{
 id:"bellatrix-collier-2", 
 dimension:"11", 
 material:"bronze", 
 size:"", 
 stone:"améthyste verte & azurites brutes",
 treatment:"doré a l’or fin", 
 weight:"79.6", 
 name:"Pendentif Tauri I", 
 price:"1200" 
}, 
{
 id:"bellatrix-collier-3", 
 dimension:"9.5", 
 material:"bronze", 
 size:"", 
 stone:"lolite & azurite brute",
 treatment:"doré a l’or fin", 
 weight:"55.2", 
 name:"Pendentif Tauri II", 
 price:"1200" 
}, 
{
 id:"bellatrix-bague-11", 
 dimension:"3.3x2.7x3.5", 
 material:"argent", 
 size:"58", 
 stone:"aigue-marine brute & azurite brute",
 treatment:"plaqué or", 
 weight:"50", 
 name:"Bague Zeta", 
 price:"1400" 
}, 
{
 id:"adama-collier-3", 
 dimension:"5.5", 
 material:"bronze", 
 size:"", 
 stone:"malachite",
 treatment:"doré a l’or fin", 
 weight:"23.8", 
 name:"Pendentif Perseï I", 
 price:"750" 
}, 
{
 id:"adama-manchette-2", 
 dimension:"6", 
 material:"bronze", 
 size:"", 
 stone:"dioptase avec signature émeraude",
 treatment:"doré a l’or fin", 
 weight:"125", 
 name:"Manchette Philos", 
 price:"1800" 
}, 

 ] 
 export default products