const products = [ 
{
 ref:"203",
 id:"bleu-bague-2", 
 dimension:"3.2x2.7x3.6", 
 material:"argent", 
 size:"55", 
 stone:"azurite et diamant noir",
 treatment:"plaque or", 
 weight:"47", 
 name:"test", 
 price:"500" 
}, 
{
 ref:"41",
 id:"bleu-bague-5", 
 dimension:"3x4x2.5", 
 material:"argent", 
 size:"57", 
 stone:"lapis lazuli",
 treatment:"plaque or", 
 weight:"36.2", 
 name:"", 
 price:"" 
}, 
{
 ref:"40",
 id:"", 
 dimension:"4.3x2.5x2.2", 
 material:"argent", 
 size:"56", 
 stone:"tourmaline",
 treatment:"plaque or", 
 weight:"36.6", 
 name:"", 
 price:"" 
}, 
{
 ref:"31",
 id:"", 
 dimension:"3x2.5x3.7", 
 material:"argent", 
 size:"55", 
 stone:"agate bleu",
 treatment:"plaque or", 
 weight:"41.3", 
 name:"", 
 price:"" 
}, 
{
 ref:"183",
 id:"bleu-bague-8", 
 dimension:"3.3x2.2x2", 
 material:"argent", 
 size:"58", 
 stone:"aigue marine",
 treatment:"plaque or", 
 weight:"33.8", 
 name:"", 
 price:"" 
}, 
{
 ref:"187",
 id:"blanche-bague-2", 
 dimension:"3.3x3.5x3", 
 material:"argent", 
 size:"55", 
 stone:"aigue marine brut",
 treatment:"plaque or", 
 weight:"44", 
 name:"", 
 price:"" 
}, 
{
 ref:"54",
 id:"bleu-bague-6", 
 dimension:"3.3x2.3x3", 
 material:"argent", 
 size:"54", 
 stone:"lapis lazuli",
 treatment:"plaque or", 
 weight:"27.5", 
 name:"", 
 price:"" 
}, 
{
 ref:"57",
 id:"", 
 dimension:"3x4x2.5", 
 material:"argent", 
 size:"57", 
 stone:"lapis lazuli",
 treatment:"plaque or ", 
 weight:"36.2", 
 name:"", 
 price:"" 
}, 
{
 ref:"33",
 id:"", 
 dimension:"3.2x2.6x2.3", 
 material:"argent", 
 size:"55", 
 stone:"malachite",
 treatment:"plaque or", 
 weight:"30.5", 
 name:"", 
 price:"" 
}, 
{
 ref:"14",
 id:"", 
 dimension:"5x3x2.8", 
 material:"argent", 
 size:"54", 
 stone:"cristal de roche",
 treatment:"argente", 
 weight:"58.6", 
 name:"", 
 price:"" 
}, 
{
 ref:"13",
 id:"argent-bague-1", 
 dimension:"5.5x3x2.5", 
 material:"argent", 
 size:"54", 
 stone:"cristal de roche",
 treatment:"argente", 
 weight:"48.5", 
 name:"", 
 price:"" 
}, 
{
 ref:"28",
 id:"blanche-bague-8", 
 dimension:"4.5x2.8x2.3", 
 material:"argent", 
 size:"54", 
 stone:"cristal de roche",
 treatment:"plaque or", 
 weight:"46.7", 
 name:"", 
 price:"" 
}, 
{
 ref:"39",
 id:"pyrite-bague-4", 
 dimension:"5x3.5x2", 
 material:"argent", 
 size:"55", 
 stone:"pyrite",
 treatment:"plaque or", 
 weight:"53.1", 
 name:"", 
 price:"" 
}, 
{
 ref:"11",
 id:"", 
 dimension:"4x3x3.5", 
 material:"bronze", 
 size:"54", 
 stone:"amethyste",
 treatment:"plaque or", 
 weight:"51.4", 
 name:"", 
 price:"" 
}, 
{
 ref:"45",
 id:"", 
 dimension:"2.7x3x2.3", 
 material:"argent", 
 size:"54", 
 stone:"turquoise",
 treatment:"plaque or", 
 weight:"30.6", 
 name:"", 
 price:"" 
}, 
{
 ref:"29",
 id:"", 
 dimension:"4x2.5x2.5", 
 material:"argent", 
 size:"55", 
 stone:"amethyste",
 treatment:"plaque or", 
 weight:"34.8", 
 name:"", 
 price:"" 
}, 
{
 ref:"188",
 id:"", 
 dimension:"3.5x3.3x2.2", 
 material:"argent", 
 size:"51", 
 stone:"kunzite",
 treatment:"plaque or", 
 weight:"40", 
 name:"", 
 price:"" 
}, 
{
 ref:"3",
 id:"blanche-bague-1", 
 dimension:"4x4x3", 
 material:"bronze", 
 size:"56", 
 stone:"quartz rutile",
 treatment:"plaque or", 
 weight:"38.7", 
 name:"", 
 price:"" 
}, 
{
 ref:"30",
 id:"blanche-bague-6", 
 dimension:"4.5x2.5x2.2", 
 material:"argent", 
 size:"55", 
 stone:"cristal de roche",
 treatment:"plaque or ", 
 weight:"41.1", 
 name:"", 
 price:"" 
}, 
{
 ref:"27",
 id:"blanche-bague-7", 
 dimension:"4.8x2.5x2.5", 
 material:"argent", 
 size:"55", 
 stone:"cristal de roche",
 treatment:"plaque or", 
 weight:"40.5", 
 name:"", 
 price:"" 
}, 
{
 ref:"25",
 id:"argent-bague-2", 
 dimension:"4.8x3x2.6", 
 material:"argent", 
 size:"56", 
 stone:"cristal de roche",
 treatment:"argente", 
 weight:"45.3", 
 name:"", 
 price:"" 
}, 
{
 ref:"182",
 id:"", 
 dimension:"3x2x1.8", 
 material:"argent", 
 size:"58", 
 stone:"malachite",
 treatment:"plaque or", 
 weight:"27", 
 name:"", 
 price:"" 
}, 
{
 ref:"179",
 id:"", 
 dimension:"4x2.5x2.7", 
 material:"argent", 
 size:"57", 
 stone:"pierre de soleil",
 treatment:"plaque or", 
 weight:"47", 
 name:"", 
 price:"" 
}, 
{
 ref:"192",
 id:"blanche-bague-4", 
 dimension:"3x2.5x5", 
 material:"argent", 
 size:"53", 
 stone:"agate cristallisee",
 treatment:"plaque or", 
 weight:"61", 
 name:"", 
 price:"" 
}, 
{
 ref:"193",
 id:"violette-bague-1", 
 dimension:"3.5x2.3x3.5", 
 material:"argent ", 
 size:"56", 
 stone:"rubis + pierre de lune",
 treatment:"plaque or", 
 weight:"54", 
 name:"", 
 price:"" 
}, 
{
 ref:"191",
 id:"blanche-bague-3", 
 dimension:"3x3x3.5", 
 material:"argent", 
 size:"53", 
 stone:"agate cristallisee",
 treatment:"plaque or", 
 weight:"58", 
 name:"", 
 price:"" 
}, 
{
 ref:"190",
 id:"", 
 dimension:"3x2.8x4", 
 material:"argent", 
 size:"58", 
 stone:"obsidienne doree",
 treatment:"plaque or", 
 weight:"60", 
 name:"", 
 price:"" 
}, 
{
 ref:"189",
 id:"blanche-bague-5", 
 dimension:"3.2x3x4", 
 material:"argent", 
 size:"58", 
 stone:"agate cristallisee",
 treatment:"plaque or", 
 weight:"56", 
 name:"", 
 price:"" 
}, 
{
 ref:"204",
 id:"", 
 dimension:"4.4x2.6x2", 
 material:"argent", 
 size:"61", 
 stone:"dioptase + emeraude",
 treatment:"plaque or", 
 weight:"34", 
 name:"", 
 price:"" 
}, 
{
 ref:"205",
 id:"", 
 dimension:"3.2x3x3.5", 
 material:"argent", 
 size:"60", 
 stone:"dioptase + emeraude",
 treatment:"plaque or", 
 weight:"37", 
 name:"", 
 price:"" 
}, 
{
 ref:"206",
 id:"", 
 dimension:"3.3x2.5x4.2", 
 material:"argent", 
 size:"59", 
 stone:"dioptase + emeraude",
 treatment:"plaque or", 
 weight:"36", 
 name:"", 
 price:"" 
}, 
{
 ref:"212",
 id:"", 
 dimension:"3.3x2.3x2.2", 
 material:"argent", 
 size:"54", 
 stone:"peidot 4.68 CT + emeraude",
 treatment:"plaque or", 
 weight:"26", 
 name:"", 
 price:"" 
}, 
{
 ref:"210",
 id:"", 
 dimension:"3.1x2.2x2", 
 material:"argent", 
 size:"54", 
 stone:"amethyste verte 18.22CT + emeraude",
 treatment:"plaque or", 
 weight:"28", 
 name:"", 
 price:"" 
}, 
{
 ref:"211",
 id:"", 
 dimension:"3.3x2.8x2.1", 
 material:"argent", 
 size:"58", 
 stone:"amethyste verte 18.22CT + emeraude",
 treatment:"plaque or", 
 weight:"40", 
 name:"", 
 price:"" 
}, 
{
 ref:"208",
 id:"argent-bague-6", 
 dimension:"3x2.4x2.5", 
 material:"argent", 
 size:"67", 
 stone:"aigue marine 13CT + diamant taille rose",
 treatment:"argent", 
 weight:"37", 
 name:"", 
 price:"" 
}, 
{
 ref:"214",
 id:"", 
 dimension:"4.2x3x2.5", 
 material:"argent", 
 size:"57", 
 stone:"grenat noir + diamant noir",
 treatment:"plaque or", 
 weight:"57", 
 name:"", 
 price:"" 
}, 
{
 ref:"215",
 id:"", 
 dimension:"3x3x2.6", 
 material:"argent", 
 size:"57", 
 stone:"topaze rose 4.85CT + rubis",
 treatment:"plaque or", 
 weight:"46", 
 name:"", 
 price:"" 
}, 
{
 ref:"207",
 id:"", 
 dimension:"3.7x3.5x2.9", 
 material:"argent", 
 size:"61", 
 stone:"grenat noir + diamant",
 treatment:"plaque or", 
 weight:"57", 
 name:"", 
 price:"" 
}, 
{
 ref:"209",
 id:"bleu-bague-7", 
 dimension:"3.7x3.9x2.7", 
 material:"argent", 
 size:"54", 
 stone:"aigue marine 81CT + aigue marine cabochon",
 treatment:"plaque or", 
 weight:"63", 
 name:"", 
 price:"" 
}, 
{
 ref:"216",
 id:"", 
 dimension:"2x2x1.5", 
 material:"argent", 
 size:"60", 
 stone:"signature diamant noir",
 treatment:"plaque or", 
 weight:"10", 
 name:"", 
 price:"" 
}, 
{
 ref:"217",
 id:"verte-bague-1", 
 dimension:"2x2x1", 
 material:"argent", 
 size:"59", 
 stone:"signature emeraude",
 treatment:"plaque or", 
 weight:"6", 
 name:"", 
 price:"" 
}, 
{
 ref:"181",
 id:"noire-bague-1", 
 dimension:"3.5x2.5x1.5", 
 material:"argent", 
 size:"58", 
 stone:"pyrite",
 treatment:"plaque or", 
 weight:"41.2", 
 name:"", 
 price:"" 
}, 
{
 ref:"200",
 id:"", 
 dimension:"", 
 material:"bronze", 
 size:"", 
 stone:"8 amethyste 2 calcedoine 1 tourmanline 1 aigue marine",
 treatment:"plaque or", 
 weight:"87.3", 
 name:"", 
 price:"" 
}, 
{
 ref:"196",
 id:"", 
 dimension:"12", 
 material:"bronze", 
 size:"", 
 stone:"7 tourmaline cabochon 55CT",
 treatment:"plaque or", 
 weight:"132.1", 
 name:"", 
 price:"" 
}, 
{
 ref:"155 ",
 id:"", 
 dimension:"", 
 material:"bronze", 
 size:"", 
 stone:"rubis chatouillant",
 treatment:"plaque or", 
 weight:"179.3", 
 name:"", 
 price:"" 
}, 
{
 ref:"35",
 id:"", 
 dimension:"", 
 material:"bronze", 
 size:"", 
 stone:"lapis lazuli",
 treatment:"plaque or", 
 weight:"216.5", 
 name:"", 
 price:"" 
}, 
{
 ref:"63",
 id:"", 
 dimension:"7", 
 material:"bronze", 
 size:"", 
 stone:"",
 treatment:"plaque or", 
 weight:"135.3", 
 name:"", 
 price:"" 
}, 
{
 ref:"195",
 id:"", 
 dimension:"", 
 material:"bronze", 
 size:"", 
 stone:"4 calcedoine 3 amethystes 2 tourmalines",
 treatment:"plaque or", 
 weight:"", 
 name:"", 
 price:"" 
}, 
{
 ref:"202",
 id:"", 
 dimension:"", 
 material:"bronze", 
 size:"", 
 stone:"grenat",
 treatment:"plaque or", 
 weight:"", 
 name:"", 
 price:"" 
}, 
{
 ref:"201",
 id:"", 
 dimension:"", 
 material:"bronze", 
 size:"", 
 stone:"azurite",
 treatment:"plaque or", 
 weight:"", 
 name:"", 
 price:"" 
}, 
{
 ref:"199",
 id:"", 
 dimension:"", 
 material:"bronze", 
 size:"", 
 stone:"tourmaline",
 treatment:"plaque or", 
 weight:"", 
 name:"", 
 price:"" 
}, 
{
 ref:"153",
 id:"", 
 dimension:"5.5x6x7", 
 material:"bronze", 
 size:"", 
 stone:"2 amethystes 1 citrine",
 treatment:"plaque or", 
 weight:"173.8", 
 name:"", 
 price:"" 
}, 
{
 ref:"96",
 id:"", 
 dimension:"12", 
 material:"bronze", 
 size:"", 
 stone:"lapis lazuli",
 treatment:"plaque or", 
 weight:"207.6", 
 name:"", 
 price:"" 
}, 
{
 ref:"53+61",
 id:"", 
 dimension:"12", 
 material:"bronze", 
 size:"", 
 stone:"pyrite",
 treatment:"plaque or", 
 weight:"176.5", 
 name:"", 
 price:"" 
}, 
{
 ref:"194",
 id:"", 
 dimension:"12", 
 material:"bronze", 
 size:"", 
 stone:"5 grenat noir + diamant noir",
 treatment:"plaque or", 
 weight:"264", 
 name:"", 
 price:"" 
}, 
{
 ref:"197",
 id:"", 
 dimension:"6x6.5x7", 
 material:"bronze", 
 size:"", 
 stone:"dioptase + emeraude",
 treatment:"plaque or", 
 weight:"125", 
 name:"", 
 price:"" 
}, 
{
 ref:"64+218",
 id:"", 
 dimension:"6x6.5x7.5", 
 material:"bronze", 
 size:"", 
 stone:"tranche d'amethyste 79.95CT + diamant noir",
 treatment:"plaque or", 
 weight:"157.2", 
 name:"", 
 price:"" 
}, 
{
 ref:"18+220 ",
 id:"", 
 dimension:"5.5x6x8.5", 
 material:"argent", 
 size:"", 
 stone:"dioptase + emeraude",
 treatment:"plaque or", 
 weight:"236.8", 
 name:"", 
 price:"" 
}, 
{
 ref:"64+219",
 id:"", 
 dimension:"9", 
 material:"bronze", 
 size:"", 
 stone:"azurite + diamant noir",
 treatment:"plaque or", 
 weight:"229.2", 
 name:"", 
 price:"" 
}, 
{
 ref:"158+222",
 id:"", 
 dimension:"7", 
 material:"argent", 
 size:"", 
 stone:"grenat noir + diamant",
 treatment:"plaque or", 
 weight:"197.5", 
 name:"", 
 price:"" 
}, 
{
 ref:"158+223",
 id:"", 
 dimension:"7", 
 material:"argent", 
 size:"", 
 stone:"grenat noir + diamant",
 treatment:"plaque or", 
 weight:"197.9", 
 name:"", 
 price:"" 
}, 
{
 ref:"18+221",
 id:"", 
 dimension:"6x6.5x9", 
 material:"argent", 
 size:"", 
 stone:"dioptase + emeraude",
 treatment:"plaque or", 
 weight:"262.4", 
 name:"", 
 price:"" 
}, 
{
 ref:"000",
 id:"", 
 dimension:"5.5x5.5x5", 
 material:"bronze", 
 size:"", 
 stone:"diamant noir",
 treatment:"plaque or", 
 weight:"192.2", 
 name:"", 
 price:"" 
}, 
{
 ref:"234",
 id:"", 
 dimension:"3.8x3.5x4.7", 
 material:"argent", 
 size:"58", 
 stone:"tourmaline 38.16 CT + aigue-marine ",
 treatment:"plaque or", 
 weight:"80", 
 name:"", 
 price:"" 
}, 
{
 ref:"231",
 id:"bleu-bague-3", 
 dimension:"3.5x2.5x3", 
 material:"argent", 
 size:"58", 
 stone:"azurite + aigue-marine",
 treatment:"plaque or", 
 weight:"40", 
 name:"", 
 price:"" 
}, 
{
 ref:"227",
 id:"pyrite-bague-5", 
 dimension:"4.2x3x2.5", 
 material:"argent", 
 size:"56", 
 stone:"pyrite + diamant noir",
 treatment:"plaque or", 
 weight:"46", 
 name:"", 
 price:"" 
}, 
{
 ref:"225",
 id:"", 
 dimension:"4x3x2.3", 
 material:"argent", 
 size:"59", 
 stone:"pyrite + diamant noir",
 treatment:"plaque or", 
 weight:"46", 
 name:"", 
 price:"" 
}, 
{
 ref:"226",
 id:"", 
 dimension:"3.5x2.5x1.4", 
 material:"argent", 
 size:"57", 
 stone:"pyrite + diamant noir",
 treatment:"plaque or", 
 weight:"40", 
 name:"", 
 price:"" 
}, 
{
 ref:"229",
 id:"pyrite-bague-3", 
 dimension:"3.5x3.3x2", 
 material:"argent", 
 size:"54", 
 stone:"proustite + diamant noir",
 treatment:"plaque or", 
 weight:"38", 
 name:"", 
 price:"" 
}, 
{
 ref:"223",
 id:"", 
 dimension:"4x2x2.2", 
 material:"argent", 
 size:"58", 
 stone:"quartz",
 treatment:"plaque or", 
 weight:"37", 
 name:"", 
 price:"" 
}, 
{
 ref:"",
 id:"bleu-bague-1", 
 dimension:"3.3x2.7x3.5", 
 material:"argent", 
 size:"58", 
 stone:"aigue marine brute + saphir",
 treatment:"plaque or", 
 weight:"50", 
 name:"", 
 price:"" 
}, 
{
 ref:"243",
 id:"", 
 dimension:"2.5x3x4.5", 
 material:"argent", 
 size:"56", 
 stone:"malachite + emeraude",
 treatment:"plaque or", 
 weight:"34", 
 name:"", 
 price:"" 
}, 
{
 ref:"239",
 id:"", 
 dimension:"11.5", 
 material:"bronze", 
 size:"", 
 stone:"dioptase + 8 lolites",
 treatment:"plaque or", 
 weight:"289", 
 name:"", 
 price:"" 
}, 
{
 ref:"240",
 id:"", 
 dimension:"12", 
 material:"bronze", 
 size:"", 
 stone:"amethyste",
 treatment:"plaque or", 
 weight:"318.2", 
 name:"", 
 price:"" 
}, 
{
 ref:"241",
 id:"", 
 dimension:"11.5", 
 material:"bronze", 
 size:"", 
 stone:"3 dioptases",
 treatment:"plaque or", 
 weight:"299.6", 
 name:"", 
 price:"" 
}, 
{
 ref:"242",
 id:"", 
 dimension:"12", 
 material:"bronze", 
 size:"", 
 stone:"malachites",
 treatment:"plaque or", 
 weight:"118.1", 
 name:"", 
 price:"" 
}, 
{
 ref:"238",
 id:"", 
 dimension:"6x6x11", 
 material:"bronze", 
 size:"", 
 stone:"malachite",
 treatment:"plaque or", 
 weight:"152.3", 
 name:"", 
 price:"" 
}, 
{
 ref:"243",
 id:"argent-bague-4", 
 dimension:"", 
 material:"argent", 
 size:"", 
 stone:"",
 treatment:"argent", 
 weight:"", 
 name:"", 
 price:"" 
}, 
{
 ref:"244",
 id:"pyrite-bague-2", 
 dimension:"3.8x2.5x2.5", 
 material:"argent", 
 size:"59", 
 stone:"pyrite",
 treatment:"argent", 
 weight:"36.5", 
 name:"", 
 price:"" 
}, 
{
 ref:"245",
 id:"argent-bague-5", 
 dimension:"3.5x3x3", 
 material:"argent", 
 size:"59", 
 stone:"amethyste verte",
 treatment:"argent", 
 weight:"45.2", 
 name:"", 
 price:"" 
}, 
{
 ref:"246",
 id:"pyrite-bague-1", 
 dimension:"3.5x2.5x2.2", 
 material:"argent", 
 size:"60", 
 stone:"pyrite",
 treatment:"argent", 
 weight:"42.1", 
 name:"", 
 price:"" 
}, 
{
 ref:"247",
 id:"argent-bague-3", 
 dimension:"3.5x2.5x2", 
 material:"argent", 
 size:"59", 
 stone:"tourmaline + aigue-marine brute",
 treatment:"argent", 
 weight:"33.8", 
 name:"", 
 price:"" 
}, 
{
 ref:"236",
 id:"", 
 dimension:"", 
 material:"bronze", 
 size:"", 
 stone:"agate cristallisee",
 treatment:"plaque or", 
 weight:"", 
 name:"", 
 price:"" 
}, 
{
 ref:"235",
 id:"", 
 dimension:"6x6.5x9", 
 material:"bronze", 
 size:"", 
 stone:"agate",
 treatment:"plaque or", 
 weight:"179.8", 
 name:"", 
 price:"" 
}, 
{
 ref:"251 B",
 id:"", 
 dimension:"5.5x3.5", 
 material:"bronze", 
 size:"", 
 stone:"malachite",
 treatment:"plaque or", 
 weight:"23.8", 
 name:"", 
 price:"" 
}, 
{
 ref:"251 A",
 id:"", 
 dimension:"4.5x2.8", 
 material:"bronze", 
 size:"", 
 stone:"malachite",
 treatment:"plaque or", 
 weight:"20.4", 
 name:"", 
 price:"" 
}, 
{
 ref:"253",
 id:"", 
 dimension:"6x6x11.5", 
 material:"bronze", 
 size:"", 
 stone:"agate cristallisee",
 treatment:"plaque or", 
 weight:"177.6", 
 name:"", 
 price:"" 
}, 
{
 ref:"254",
 id:"", 
 dimension:"6x7.5x7", 
 material:"bronze", 
 size:"", 
 stone:"obsidienne",
 treatment:"plaque or", 
 weight:"163.3", 
 name:"", 
 price:"" 
}, 
{
 ref:"38",
 id:"verte-bague-2", 
 dimension:"3x3x2", 
 material:"argent", 
 size:"54", 
 stone:"amethyste verte",
 treatment:"plaque or", 
 weight:"36.6", 
 name:"", 
 price:"" 
}, 
{
 ref:"198",
 id:"", 
 dimension:"6x6x6.5", 
 material:"bronze", 
 size:"", 
 stone:"2 azurite brute",
 treatment:"plaque or", 
 weight:"151.9", 
 name:"", 
 price:"" 
}, 
{
 ref:"26",
 id:"bleu-bague-4", 
 dimension:"3.3x2.3x3", 
 material:"argent", 
 size:"54", 
 stone:"lapis lazuli",
 treatment:"plaque or", 
 weight:"27.5", 
 name:"", 
 price:"" 
}, 

 ] 
 export default products